trigger:
    - dev

pool:
    vmImage: "ubuntu-latest"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "10.x"
      displayName: "Install Node.js"

    - script: |
          npm install
          npm run build
      displayName: "npm install and build"

    - script: |
          npm test
      displayName: "npm test"

    - script: |
          npm run pack:canary
      displayName: "npm pack:canary"

    - script: |
          mkdir $(Build.ArtifactStagingDirectory)/packages
          mv packages/**/*.tgz $(Build.ArtifactStagingDirectory)/packages
      displayName: "Move tgz to artifacts folder"

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact: packages"
      inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/packages"
          ArtifactName: packages

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact: lerna.json"
      inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)/lerna.json"
          ArtifactName: lerna
